# Generated by Django 5.2.4 on 2025-11-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sellers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerprofile",
            name="delivery_radius",
            field=models.IntegerField(default=120, help_text="Delivery radius in km"),
        ),
    ]
