# Generated by Django 5.2.4 on 2025-11-27 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sellers", "0002_sellerprofile_delivery_radius"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sellerprofile",
            name="postal_code",
        ),
    ]
