# Generated by Django 5.2.4 on 2025-12-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sellers", "0003_remove_sellerprofile_postal_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sellerprofile",
            name="is_verified",
            field=models.BooleanField(
                default=False, help_text="Has admin approved this seller?"
            ),
        ),
    ]
