# Generated by Django 5.2.4 on 2026-03-02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import customers.models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_notification"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NegotiatedOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("negotiated_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("completed", "Completed"), ("cancelled", "Cancelled")], default="pending", max_length=20)),
                ("expires_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("buyer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="negotiated_orders", to=settings.AUTH_USER_MODEL)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="negotiated_orders", to="products.product")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="negotiatedorder",
            constraint=models.UniqueConstraint(condition=models.Q(("status", "pending")), fields=("buyer", "product"), name="unique_pending_negotiated_order_per_buyer_product"),
        ),
    ]
