# Generated by Django 5.2.4 on 2026-03-02 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_negotiatedorder"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NegotiatedOrder",
        ),
    ]
